#!/usr/bin/python
#
# Check_MK Puppet Plugin - Checks the status of the Puppet agent.
#
# Copyright 2010, Stefan Schlesinger <sts@ono.at>
#
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

import sys
import os
import datetime

# Return the number of seconds since the last puppet run,
# or false if puppet was never run.
def lastrun(statefile):
    if not os.path.isfile(statefile):
        return False

    # Calculate the delta from now - statefile mtime
    now     = datetime.datetime.now()
    mtime   = datetime.datetime.fromtimestamp(os.path.getmtime(statefile))
    delta   = now - mtime

    return delta.seconds


def is_disabled(s):

    if s.disabled:
        return [ True, "%s" % s.reason ]
    else:
        return [ False ]


def main():
    puppetlib = '/var/lib/puppet'
    statefile = '/var/lib/puppet/state/state.yaml'
    seconds   = lastrun(statefile)

    if not os.path.isdir(puppetlib):
        return

    try:
        import puppetstatus
        s = puppetstatus.PuppetStatus()
        disabled = is_disabled(s)
    except ImportError:
        sys.exit()
        # DO SOMETHING

    print "<<<puppet>>>"
    print "agent lastrun %s" % seconds
    print "agent disabled %s" % disabled[0]
    if disabled[0]:
        print "agent disabled-reason \"%s\"" % disabled[1]

if __name__ == "__main__":
    main()
